# Site settings
title: Game Developer
email: lekrieggamedev@gmail.com
description: > # keep this and put description below
  Programmer and game designer
url: "https://lekrieg.itch.io/" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/daniel-henrique-silva-167375132/"
github_username: lekrieg
# twitter_username: gamingportfolio
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
